# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Configuracao(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(472, 135)
        Form.setMinimumSize(QtCore.QSize(472, 135))
        Form.setMaximumSize(QtCore.QSize(472, 135))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("background-color: rgb(118, 118, 118);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 581, 51))
        self.frame_2.setStyleSheet("background-color: rgb(133, 0, 153);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(140, -50, 211, 171))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/config/config.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Doc_2 = QtWidgets.QLabel(self.frame)
        self.Doc_2.setGeometry(QtCore.QRect(10, 80, 131, 21))
        font = QtGui.QFont()
        font.setFamily("OMEGLE")
        font.setPointSize(12)
        self.Doc_2.setFont(font)
        self.Doc_2.setObjectName("Doc_2")
        self.tempo_sleep = QtWidgets.QSpinBox(self.frame)
        self.tempo_sleep.setGeometry(QtCore.QRect(140, 81, 41, 21))
        self.tempo_sleep.setObjectName("tempo_sleep")
        self.Doc_3 = QtWidgets.QLabel(self.frame)
        self.Doc_3.setGeometry(QtCore.QRect(186, 81, 21, 21))
        font = QtGui.QFont()
        font.setFamily("OMEGLE")
        font.setPointSize(12)
        self.Doc_3.setFont(font)
        self.Doc_3.setObjectName("Doc_3")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Configuração"))
        self.Doc_2.setText(_translate("Form", "Tempo de espera"))
        self.Doc_3.setText(_translate("Form", "ms"))
import template.config_tela


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Configuracao()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
