# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(244, 164)
        Form.setMinimumSize(QtCore.QSize(244, 164))
        Form.setMaximumSize(QtCore.QSize(244, 164))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_2.setStyleSheet("background-color: rgb(133, 0, 153);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(70, -35, 101, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/user/usuario_portal.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("background-color: rgb(118, 118, 118);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.email = QtWidgets.QLabel(self.frame)
        self.email.setGeometry(QtCore.QRect(90, 1, 41, 16))
        font = QtGui.QFont()
        font.setFamily("OMEGLE")
        font.setPointSize(12)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.email_edit = QtWidgets.QLineEdit(self.frame)
        self.email_edit.setGeometry(QtCore.QRect(10, 20, 211, 21))
        self.email_edit.setStyleSheet("frame-color: rgb(111, 111, 111);")
        self.email_edit.setFrame(True)
        self.email_edit.setCursorPosition(0)
        self.email_edit.setDragEnabled(False)
        self.email_edit.setReadOnly(False)
        self.email_edit.setPlaceholderText("")
        self.email_edit.setClearButtonEnabled(False)
        self.email_edit.setObjectName("email_edit")
        self.senha_edit = QtWidgets.QLineEdit(self.frame)
        self.senha_edit.setGeometry(QtCore.QRect(10, 60, 210, 20))
        self.senha_edit.setText("")
        self.senha_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senha_edit.setObjectName("senha_edit")
        self.senha = QtWidgets.QLabel(self.frame)
        self.senha.setGeometry(QtCore.QRect(90, 42, 51, 16))
        font = QtGui.QFont()
        font.setFamily("OMEGLE")
        font.setPointSize(12)
        self.senha.setFont(font)
        self.senha.setObjectName("senha")
        self.botao_salvar = QtWidgets.QPushButton(self.frame)
        self.botao_salvar.setGeometry(QtCore.QRect(70, 90, 91, 23))
        self.botao_salvar.setObjectName("botao_salvar")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Usuário Portal"))
        self.email.setText(_translate("Form", "Email"))
        self.senha.setText(_translate("Form", "Senha"))
        self.botao_salvar.setText(_translate("Form", "Salvar"))
import template.tela_user


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
